// Copyright (c) 2018 Veriktig.  All rights reserved.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT

package com.veriktig.scandium.internal.test.help;

import java.util.ListResourceBundle;

public class Help_en_US extends ListResourceBundle {
    protected Object[][] getContents() {
        return new Object[][] {
            {"internal_test", "Runs tests on commands."}
        };
    }
}
