// Copyright (c) 2018 Veriktig.  All rights reserved.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT

package com.veriktig.scandium.api.help;

import java.util.ListResourceBundle;

public class Help_en_US extends ListResourceBundle {
    protected Object[][] getContents() {
        return new Object[][] {
            {"print_versions", "Displays the installed bundles and version information."},
            {"help", "Displays a concise description of a command."},
            {"printvar", "Displays the value of variables."}
        };
    }
}
