// Copyright (c) 2018 Veriktig.  All rights reserved.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT

package com.veriktig.scandium.api.errors;

import java.util.ListResourceBundle;

import com.veriktig.scandium.api.errors.ErrorMessage;
import com.veriktig.scandium.api.SCAPI;

public class Errors_en_US extends ListResourceBundle {
    protected Object[][] getContents() {
        return new Object[][] {
            {"API-1000", new ErrorMessage(SCAPI.ErrorType.ERROR, "Wrong number of arguments.")},
            {"API-1001", new ErrorMessage(SCAPI.ErrorType.ERROR, "%s is a file, not a directory.")},
            {"API-1002", new ErrorMessage(SCAPI.ErrorType.ERROR, "Error unmarshaling XML source file %s: %s")},
            {"API-1003", new ErrorMessage(SCAPI.ErrorType.ERROR, "File %s does not exist.")},
            {"API-1004", new ErrorMessage(SCAPI.ErrorType.ERROR, "Package %s: Whitespace not allowed in Names: %s")},
            {"API-1005", new ErrorMessage(SCAPI.ErrorType.ERROR, "Package %s: Slash is not allowed in Names: %s")},
            {"API-1006", new ErrorMessage(SCAPI.ErrorType.ERROR, "Package %s: Reserved word null found in Name.")},
            {"API-1007", new ErrorMessage(SCAPI.ErrorType.ERROR, "Package %s: Reserved word %s from %s found in Name.")},
            {"API-1008", new ErrorMessage(SCAPI.ErrorType.ERROR, "Package %s: Undefined attribute Name.")},
            {"API-1009", new ErrorMessage(SCAPI.ErrorType.ERROR, "Unable to create %s: %s")},
            {"API-1010", new ErrorMessage(SCAPI.ErrorType.ERROR, "Unable to create PrintWriter: %s")},
            {"API-1011", new ErrorMessage(SCAPI.ErrorType.ERROR, "Unable to close BufferedReader: %s")},
            {"API-1012", new ErrorMessage(SCAPI.ErrorType.ERROR, "Directory does not exist: %s")},
            {"API-1013", new ErrorMessage(SCAPI.ErrorType.ERROR, "Application variable interface_delimiter is not allowed in Names: %s")},
            {"API-1014", new ErrorMessage(SCAPI.ErrorType.ERROR, "Unable to read from file: %s")}
        };
    }
}
